In [1]:
import numpy as np
import scipy.special
import matplotlib.pyplot
%matplotlib inline

In [2]:
# 定义一个class
class NeuralNetwork:
    def __init__(self,inputnodes,hiddennodes,outputnodes,learningrate) -> None:
        self.inodes = inputnodes
        self.onodes = outputnodes
        self.hnodes = hiddennodes

        # layers
        # i -> h -> o
        self.wih = np.random.normal(0.0,pow(self.inodes, -0.5),(self.hnodes,self.inodes))
        self.who = np.random.normal(0.0,pow(self.hnodes, -0.5),(self.onodes,self.hnodes))

        # 学习曲线
        self.lr = learningrate

        # 激活函数
        self.actfunc = lambda x:scipy.special.expit(x)

        pass

    def train(self,inputs_list,targets_list):
        # 将输入数据 转换为二维矩阵
        inputs = np.array(inputs_list,ndmin=2).T
        targets = np.array(targets_list,ndmin=2).T

        # 权重计算
        hidden_inputs = np.dot(self.wih,inputs)
        # 激活函数
        hidden_outputs = self.actfunc(hidden_inputs)

        final_inputs = np.dot(self.who,hidden_outputs)
        final_outputs = self.actfunc(final_inputs)

        output_errors = targets - final_outputs
        hidden_errors = np.dot(self.who.T,output_errors)

        # 更新权重
        self.who += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)),np.transpose(hidden_outputs))
        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)),np.transpose(inputs))
    
        pass


    def quary(self,input_list):
        inputs = np.array(input_list,ndmin=2).T
        # 将输入的input 转化为2维度

        # 计算进入hidden的信号
        hidden_inputs = np.dot(self.wih,inputs)
        # 计算从hidden出来的信号 激活函数
        hidden_outputs = self.actfunc(hidden_inputs)

        # 计算最终进去output的信号
        final_inputs = np.dot(self.who,hidden_outputs)
        final_outputs = self.actfunc(final_inputs)

        return final_outputs



In [3]:
input_nodes = 784
hidden_nodes = 200
output_nodes = 10

learning_rate = 0.1

n = NeuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate)
# 创建神经网络 

In [4]:
# 载入数据
training_data_file = open("mnist_dataset/mnist_train_100.csv",'r')
training_data_list = training_data_file.readlines()
training_data_file.close()

In [5]:
# 循环时间
epochs = 5

for e in range(epochs):
    for record in training_data_list:
        all_value = record.split(',')

        inputs = (np.asfarray(all_value[1:]) / 255.0 * 0.99) + 0.01
        targets = np.zeros(output_nodes) + 0.01

        # 标签标志为0.99 用来后序
        targets[int(all_value[0])] = 0.99

        n.train(inputs,targets)

        pass
    pass




In [6]:
test_data_file = open("mnist_dataset/mnist_test_10.csv",'r')
test_data_list = test_data_file.readlines()
test_data_file.close()
test_data_list[0]

'7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,84,185,159,151,60,36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,222,254,254,254,254,241,198,198,198,198,198,198,198,198,170,52,0,0,0,0,0,0,0,0,0,0,0,0,67,114,72,114,163,227,254,225,254,254,254,250,229,254,254,140,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,66,14,67,67,67,59,21,236,254,106,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,83,253,209,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,233,255,83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,129,254,238,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,59,249,254,62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,133,254,187,5,0,

In [7]:
scorecard = []
for record in test_data_list:
    all_value = record.split(',')

    correct_label = int(all_value[0])

    inputs = (np.asfarray(all_value[1:]) / 255.0 * 0.99) + 0.01
    outputs = n.quary(inputs)
    print(outputs)
    
    label = np.argmax(outputs)
    print(label)

    if(label == correct_label):
        scorecard.append(1)
    else:
        scorecard.append(0)
    pass



[[0.09874471]
 [0.03184192]
 [0.0591251 ]
 [0.09143815]
 [0.09861322]
 [0.04022069]
 [0.01350844]
 [0.68462642]
 [0.081803  ]
 [0.08425004]]
7
[[0.32377486]
 [0.07149042]
 [0.23483747]
 [0.20096306]
 [0.01524083]
 [0.0536187 ]
 [0.24284372]
 [0.03238489]
 [0.11235912]
 [0.01115807]]
0
[[0.02149593]
 [0.87075152]
 [0.05458266]
 [0.10894422]
 [0.06083903]
 [0.09270003]
 [0.07102028]
 [0.12028893]
 [0.1157691 ]
 [0.03803961]]
1
[[0.69305248]
 [0.01197605]
 [0.06546019]
 [0.03056073]
 [0.03053049]
 [0.0245342 ]
 [0.12089014]
 [0.17571645]
 [0.03584329]
 [0.01161184]]
0
[[0.05992848]
 [0.01893805]
 [0.07843561]
 [0.0743467 ]
 [0.72086254]
 [0.03755602]
 [0.04911851]
 [0.33169019]
 [0.05431564]
 [0.04076954]]
4
[[0.01670084]
 [0.89831827]
 [0.04659216]
 [0.10320121]
 [0.04605846]
 [0.0791075 ]
 [0.03245084]
 [0.12908818]
 [0.13362819]
 [0.03158532]]
1
[[0.01853993]
 [0.01851062]
 [0.04398368]
 [0.12042593]
 [0.43917363]
 [0.05376164]
 [0.04391367]
 [0.26129717]
 [0.11119809]
 [0.11681896]]
4

In [8]:
scorecard_array = np.asfarray(scorecard)
scorecard_array

array([1., 0., 1., 1., 1., 1., 1., 0., 0., 0.])

In [9]:
performence = scorecard_array.sum() / scorecard_array.size
print("performence =",performence)


performence = 0.6
